import React from "react";
import { Paper } from "@material-ui/core";
import classes from "./index.module.scss";

type Props = {};

const FocusHome: React.FC<Props> = (props) => {
  return (
    <div className={classes.filterannot}>
      <Paper variant={"outlined"} elevation={3} className={classes.paper}>
        <p>
          The aim of this pipeline is to perform functional prediction of
          variants. We provide four different annotation which are: the Combined
          Annotation Dependent Depletion score (CADD), the genome-wide
          annotation of variants that supports prioritization of noncoding
          variants by integrating various genomic and epigenomic annotations
          (GWAVA), the functional prediction score generated by deep learning
          (DANN), the functional prediction scores for mutations based on
          selective constraints across human genome (GERP++), and the spectral
          approach integrating functional genomic annotations for coding and
          noncoding variants (EIGEN). All these five annotations which are
          provided in this tool are based on the hg19 genome build. CADD, GWAVA,
          GERP++, and EIGEN provide scores of 9 billion mutations.
        </p>
        <h3>Input</h3>
        <p>The input file for this pipeline is a plain text file  in Annovar input file format (avinput).  This input file is without a header line and the required fields in any avinput file are:</p>
        <ol>
          <li>1st field is for chromosome number of the variant, i.e. without the prefix ‘chr’.
          </li>
          <li>The 2nd field is for a variant start site.</li>
          <li>The 3rd field is for a variant stop site.</li>
          <li>The 4th field is for the reference allele.</li>
          <li>The 5th field is for the alternative allele. </li>
        </ol>
        <p>Any fields apart from the five 5 fields will not be included to perform the annotation process;however, they will be appended in the output file.</p>
        <p>Obs: Users can use the hyphen symbol (-) for the deletion events in alleles.</p>
        <h3>Input options:</h3>
        <p>Users should specify only the name of the annotation resource, i.e., choose  CADD, GWAVA, DANN, GERP, or EIGEN.</p>
        <h3>Output file</h3>
        <p>This pipeline reports the output into two plain text files:</p>
        <ol>
          <li>A file contains information about known  variants based on the selected source of the annotation database. This file will be written to the dropped.txt file.</li>
          <li>The variants without matching database entries will be written to the filtered.txt file.</li>
        </ol>
      </Paper>
    </div>
  );
};

export default FocusHome;
