export enum ActionType {
  AUTH_START = "auth_start",
  AUTH_SUCCESS = "auth_success",
  AUTH_ERROR = "auth_error",
  SIGNUP_START = "signup_start",
  SIGNUP_SUCCESS = "signup_success",
  SIGNUP_ERROR = "signup_error",
  CURRENT_USER_START = "current_user_start",
  CURRENT_USER_SUCCESS = "current_user_success",
  CURRENT_USER_ERROR = "current_user_error",
  SIGNOUT_START = "signout_start",
  SIGNOUT_SUCCESS = "signout_success",
  SIGNOUT_ERROR = "signout_error",
  MINIFIED_LAYOUT = "MINIFIED_LAYOUT",
  ANNOTATION_RESULT_START = "annotation_result_start",
  ANNOTATION_RESULT_SUCCESS = "annotation_result_success",
  ANNOTATION_RESULT_ERROR = "annotation_result_error",
}
