name: deploy-frontend

on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend && docker build -t cubrenig/pgwasfrontendapp:latest -t cubrenig/pgwasfrontendapp:$GITHUB_SHA .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push cubrenig/pgwasfrontendapp:latest
      - run: docker push cubrenig/pgwasfrontendapp:$GITHUB_SHA
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-21-2-do-2-fra-pgwas
      - run: helm upgrade pgwasfrontendapp ./deployment/helm-micro/ --install --wait --set image=cubrenig/pgwasfrontendapp:$GITHUB_SHA --values=./deployment/helm-micro/client-values.yaml
